### ISSUE TITLE
doesn't build (ubuntu 20.04, msbuild 16.6.0)

### ISSUE THREAD

**Issue by hellidox** [alexcodito/StickFightTheGameTrainer#1]
[msbuild.log](https://github.com/alexcodito/StickFightTheGameTrainer/files/8457552/msbuild.log)
`nuget restore StickFightTheGameTrainer.sln ; msbuild`

**Comment by alexcodito** [comment]
The project's in .NET Framework. As far as I know, cross-platform building (e.g. on Linux) only works for .NET Core or .NET Standard.
