### ISSUE TITLE
csc.exe problem

### ISSUE THREAD

**Issue by Irqendjemand** [alexcodito/StickFightTheGameTrainer#6]
When I tried to run the exe and then pressed Install Mod, I got an error message that the csc.exe file could not be found. After that I looked in the Windows files and found it there. Why does the exe not recognize the file?

**Comment by alexcodito** [comment]
Try running this in the Package Manager Console:

> Tools > Nuget Package Manager > Package Manager Console

`Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r`

If that doesn't work, make sure you've installed .NET Framework SDK 4.6.1

**Comment by yummsys** [comment]
I'm having the same problem but I'm not a tech nerd and I have no idea how to get Nuget Package Manager. Can you tell me what it is and where to get it?

**Comment by Kleik0** [comment]
any luck?

**Comment by alexcodito** [comment]
I don't understand why you'd try to build the code manually as a "non tech nerd" when you could just download it directly:

https://www.moddb.com/mods/stick-fight-online-trainer-loxa/downloads/stick-fight-online-trainer-loxa
